version: '3.8'

services:
  app:
    build: .
    ports:
      - "3200:3200"
    environment:
      DATABASE_DSN: "postgres://postgres:postgres@db:5432/test-db?sslmode=disable"
      GRPC_ADDRESS: ":3200"
      GRPC_OPERATION_TIMEOUT: "5s"
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: test-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
